add 09
kabuku/WebGL_samples pull request #8
Opened 2021-11-26 12:07 UTC by ktaka

09の法線マップ対応してみました。
C++版と同様の表示結果は得られていますが、私はJavaScriptは素人なのでコードの中身はガシガシ指摘していただければ。。。

2021-11-29 07:30 UTC, naotaro0123 requested changes
ありがとうございました、tga.jsいいですね。
リンクのラベル番号だけ修正お願いします

2021-11-29 07:30 UTC, naotaro0123 commented on 09/base.html
> +    <title>ggsample08</title>
ggsample09に修正お願いします。L21とL22の方も（あとsolution.html側も）

2021-11-29 07:30 UTC, naotaro0123 commented on 09/base.html
> +      // gl.generateMipmap(gl.TEXTURE_2D);
ここのコメントアウトは不要という事でしょうか（このサンプルだとあってもなくてもあまり変わらなそうですが）

2021-11-30 05:39 UTC, ktaka commented on 09/base.html
> +    <title>ggsample08</title>
修正しました。

2021-11-30 05:40 UTC, ktaka commented on 09/base.html
> +      // gl.generateMipmap(gl.TEXTURE_2D);
不要なので削除しました。

2021-11-30 05:49 UTC, merged